# Generated by flare-routegen. Do not edit.
# flare-routegen: format=1 renderer=comptime

from flare.http import ComptimeRoute, Extracted, Method, Request, Response
from my_app.views.home import home as _frg_my_app_views_home_home
from my_app.views.users import GetUser as _frg_my_app_views_users_GetUser


def _frg_wrap_my_app_views_home_home(req: Request) raises -> Response:
    return _frg_my_app_views_home_home(req)


def _frg_wrap_my_app_views_users_GetUser(req: Request) raises -> Response:
    return Extracted[_frg_my_app_views_users_GetUser]().serve(req)


comptime ROUTES: List[ComptimeRoute] = [
    ComptimeRoute(Method.GET, "/", _frg_wrap_my_app_views_home_home),
    ComptimeRoute(
        Method.GET, "/users/:id", _frg_wrap_my_app_views_users_GetUser
    ),
    ComptimeRoute(
        Method.HEAD, "/users/:id", _frg_wrap_my_app_views_users_GetUser
    ),
]
