"""Compile-time route table renderer."""

from flare_routegen.diagnostics import Diagnostic
from flare_routegen.discover import join_lines, sort_routes
from flare_routegen.models import DiscoveredRoute
from flare_routegen.module_map import (
    any_struct_handler,
    handler_import_alias,
    handler_wrapper_name,
    unique_handlers_sorted,
    validate_handler_aliases,
    wrapper_call_line,
)

comptime GENERATED_MARKER_1 = "# Generated by flare-routegen. Do not edit."
comptime GENERATED_MARKER_2 = "# flare-routegen: format=1 renderer=comptime"


def flare_method_token(method: String) -> String:
    return "Method." + method


def quote_path(path: String) -> String:
    return '"' + path + '"'


def render_comptime(
    routes: List[DiscoveredRoute],
) raises -> Tuple[String, List[Diagnostic]]:
    var alias_errors = validate_handler_aliases(routes)
    if len(alias_errors) > 0:
        return ("", alias_errors^)

    var sorted_routes = List[DiscoveredRoute]()
    for route in routes:
        sorted_routes.append(route.copy())
    sort_routes(sorted_routes)

    var lines = List[String]()
    lines.append(GENERATED_MARKER_1)
    lines.append(GENERATED_MARKER_2)
    lines.append("")
    if any_struct_handler(sorted_routes):
        lines.append(
            "from flare.http import ComptimeRoute, Extracted, Method,"
            " Request, Response"
        )
    else:
        lines.append(
            "from flare.http import ComptimeRoute, Method, Request, Response"
        )

    var handlers = unique_handlers_sorted(sorted_routes)
    for handler in handlers:
        var module_path = handler[0]
        var handler_symbol = handler[1]
        var import_alias = handler_import_alias(module_path, handler_symbol)
        lines.append(
            "from "
            + module_path
            + " import "
            + handler_symbol
            + " as "
            + import_alias
        )

    lines.append("")
    for handler in handlers:
        var module_path = handler[0]
        var handler_symbol = handler[1]
        var handler_kind = handler[2]
        var import_alias = handler_import_alias(module_path, handler_symbol)
        var wrapper = handler_wrapper_name(module_path, handler_symbol)
        lines.append("def " + wrapper + "(req: Request) raises -> Response:")
        lines.append(wrapper_call_line(import_alias, handler_kind))
        lines.append("")

    lines.append("comptime ROUTES: List[ComptimeRoute] = [")
    for i in range(len(sorted_routes)):
        var route = sorted_routes[i].copy()
        var wrapper = handler_wrapper_name(
            route.module_path, route.handler_symbol
        )
        lines.append(
            "    ComptimeRoute("
            + flare_method_token(route.method)
            + ", "
            + quote_path(route.path)
            + ", "
            + wrapper
            + "),"
        )
    lines.append("]")

    return (join_lines(lines) + "\n", List[Diagnostic]())
